Bug 1007769 - Load widget before menu
On the /search page you would sometimes get the following errors:

TypeError: t.widget is not a function
  jquery.ui.menu.js
TypeError: t(...).addClass(...).appendTo(...).menu is not a function
  jquery.ui.autocomplete.js

I think this is because the menu depends on widget, but that dependency
was not set in the requirejs config.